services:
  - postgresql
addons:
  postgresql: "11.3"
env:
  global:
    - secretKey=dsakjdfeeyf82394sndkfn
    - URL=http://localhost:2000
    - PORT=2000
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432/automart
language: node_js
node_js:
  - 10.15.3
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database automart;' -U postgres
  - npm run db
script:
  - npm test
after_success:
  - npm run coverage