import express from "express";
import carController from "../controllers/car";
import admin from "../middleware/admin";
import auth from "../middleware/auth";
import cloudinary from "../middleware/cloudinary";
import validateCar from "../helper/carValidation";
const router = express.Router();
const {createCarPost} = validateCar;
const {makePurchaseOrder} = validateCar;
const {validatePurchaseOrder} = validateCar;
const {validateMake} = validateCar;

router.post("/car", cloudinary, createCarPost, carController.addCarPost);
router.post("/order", makePurchaseOrder, carController.purchaseOrder);
router.patch("/order/:id/price",validatePurchaseOrder,carController.updatePriceOfOrder);
router.patch("/car/:id/status", carController.markPosted);
router.patch("/car/:id/price",validatePurchaseOrder, carController.updateCarPrice);
router.get("/car/:id", carController.viewSpecificCar);
router.delete("/car/:id", [auth, admin], carController.deleteCar);
router.post("/flag", carController.flagAsFraudulent);
router.get("/car", validateMake, carController.viewCar);
export default router;
